<body>
 
  <figure class="card">
    <figcaption>
      <h2>LATAR <span>BELAKANG</span></h2>
      <p>Sebagian besar wilayah di Jawa Tengah memiliki indeks risiko bencana longsor cukup tinggi. Salah satu diantaranya adalah Kabupaten Kendal. Berdasarkan data dari Badan Penanggulangan Bencana Daerah (BPBD) Kabupaten Kendal, dalam 10 tahun terakhir wilayah ini memiliki riwayat longsor sebanyak 177 titik. Berdasarkan data dari BPBD Kabupaten Kendal dan pengamatan lapangan pada bulan Januari sampai Mei 2020 ditemukan tidak kurang dari 30 titik lokasi longsor. Hal tersebut menunjukkan bahwa longsor merupakan masalah yang tidak bisa dianggap remeh karena banyak menimbulkan kerugian. Intensitas kejadian longsor yang tergolong cukup tinggi ini maka diperlukan pembaruan penelitian sebagai langkah mitigasi bencana, pembaruan data dan informasi, serta rekomendasi pengembangan wilayah. </p>
      <p>Seiring dengan pembaruan dan perkembangan teknologi, penginderaan jauh banyak digunakan untuk penelitian dalam berbagai bidang termasuk geologi, terutama dalam skala yang luas. Beberapa diantara adalah Nichol, dkk. (2005 dan 2007) menggunakan citra SPOT dan IKONOS untuk deteksi longsor di Lantau, Hongkong. Sukojo, dkk. (2018) menggunakan beberapa citra satelit yang salah satunya citra SPOT untuk analisis longsor di daerah Tuban dengan  metode pembobotan. Zhong, dkk. (2019) menjelaskan dalam penelitiannya tentang manfaat dan tantangan penginderaan jauh untuk pemetaan longsor, baik dalam mengidentifikasi bentukan maupun peta zona longsor menggunakan citra resolusi sangat tinggi (Lidar, DinSAR). Cheng, dkk. (2003) membuat penelitian mengenai identifikasi longsor dari citra multi-temporal dari beberapa tahun di Taiwan menggunakan citra resolusi tinggi SPOT. Dari beberapa penelitian tersebut membuktikan bahwa penggunaan metode penginderaan jauh dengan berbagai macam citra sesuai keperluan dianggap efektif dan banyak digunakan untuk identifikasi pada wilayah luas</p>
      <p>Penelitian potensi longsor di Kabupaten Kendal menggunakan data citra resolusi tinggi yang sudah ditajamkan sehingga resolusi spasialnya menjadi 5-8 meter.  Citra Landsat 8 yang dinilai salah satu citra resolusi tinggi yang tepat untuk mengidentifikasi penggunaan lahan pada skala yang cukup luas seperti kabupaten atau kota. Metode kalkulasi disesuaikan dengan kondisi daerah penelitian, dimana terdapat beberapa aspek seperti penggunanan lahan, indikasi kelurusan, jenis batuan, curah hujan, dan kemiringan lereng. Semua hal tersebut dianggap mempengaruhi terjadinya longsor. Parameter-parameter tersebut dikalkulasikan pada klasifikasi yang tepat menurut Direktorat Vulkanologi dan Mitigasi Bencana Geologi (DVMBG) tahun 2004, Balai Besar Penelitian dan Pengembangan Sumberdaya Pertanian (BBPPSDLP) tahun 2009, dan Pusat Vulknaologi dan Bencana Geologi (PVMBG) tahun 2015. Hal ini diperkuat oleh penelitian Dewi, dkk (2017) yang memakai metode tersebut. Beberapa data lain yakni curah hujan yang didapatkan dari satelit Himawari-8 tahun 2019, interpretasi litologi dan kelurusan yang divalidasi dengan data dari Pusat Survey Geologi tahun 2013 serta validasi lapangan, kemiringan lereng dari data Digital Elevation Model (DEM), serta interpretasi penggunaan lahan dari citra SPOT. Tujuan akhir dari penelitian ini untuk menghasilkan peta zona rawan longsor disertai dengan pengecekan lapangan, sehingga peta ini diharapkan menjadi acuan untuk berbagai pihak dalam merencanakan mitigasi bencana serta rekomendasi wilayah dalam perencanaan pembangunan.</P>
</figure>

</body>
