<body>
 
  <figure class="card">
    <figcaption>
      <h2>LATAR <span>BELAKANG</span></h2>
      <p>Kabupaten Sleman merupakan kabupaten yang terletak diantara 110° 33′ 00″ dan 110° 13′ 00″ Bujur Timur, 7° 34′ 51″ dan 7° 47′ 30″ Lintang Selatan dengan ketinggian antara 100 – 2.500 meter di atas permukaan air laut. Secara geografis Kabupaten Sleman adalah salah satu kabupaten yang memiliki perbatasan wilayah berupa Gunung api yaitu Gunung Merapi. Gunung Merapi merupakan gunungapi teraktif di dunia dengan catatan periode letusan 4 tahun sekali. Gunung merapi sendiri berbentuk sebuah kerucut dengan komposisi magma basaltik andesit. Morfologi bagian puncaknya dicirikan oleh kawah yang berbentuk tapal kuda. (BPBD Kab.Sleman, 2020)</p>
      <p>Letusan Gunung Merapi dicirikan oleh keluarnya magma kepermukaan yang berbentuk kubah lava dan berada di tengah kawah aktif di sekitar puncak. Munculnya lava ini, disertai dengan pengrusakan lava lama yang menutup aliran, sehingga terjadinya guguran lava. Lava baru yang membentuk sebuah kubah ini bisa tumbuh membesar yang menyebabkan ketidakstabilan posisi yang berakibat kubah lava tersebut didorong oleh tekanan gas dari dalam dan berakibat longsor, sehingga terjadinya awan panas yang mengalir secara gravitasi menyusuri lembah sungai. Awan panas hasil guguran kubah lava ini yang akan menjadi bahaya utama. (BPBD Kab. Sleman,2020).</P>
      <p> Terkait hal tersebut, perlu adanya upaya yang dilakukan untuk menngurangi risiko bencana yang terjadi di Gunung Merapi. Pengurangan risiko bencana (PRB) Gunung merapi dilakukan untuk menguranngi dampak buruk yang mungkin timbul, terutama dilakukan dalam situasi sedang tidak terjadi bencana, meliputi pengenalan dan pemantauan risiko bencana, perencanaan partisipasif penanggulangan bencana, pengembangan budaya sadar bencana, peningkatan komitmen terhadap pelaku penanggulangan bencana dan penerapan upaya fisik, nonfisik dan pengaturan penanggulangan bencana. (Sarwidi, 2013).</p>
      <p> Dengan adanya permasalahan tersebut seiring berkembanganya teknologi informasi yang pesat, SIG (Sistem Informasi Geografis), menjadi salah satu sarana alternatif penting untuk melakukan sistem informasi manajemen bencana dalam pemantauan gunung berapi ( Jaelani LM. Dkk 2011). Menurut Faizana, Nugraha, & Yuwono, 2015 mengemukaan bahwa perkembangan Sistem Informasi Geografis (SIG) dapat memberikan informasi data geospasial secara akurat dan menjelaskan sistem analisis yang akurat. Sehingga terdapat upaya mitigasi guna mencegah risiko yang berpotensi menjadi bencana atau meminimalisir kerugian dari bencana yang terjadi. </p>
 
</figure>

</body>
